# Generated by Django 4.2.6 on 2023-10-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderproduct',
            table='order_product',
        ),
        migrations.AlterModelTable(
            name='orderproductvoucher',
            table='order_product_voucher',
        ),
    ]
